/*
THIS FILE CONTAINS SQL SENTENCES INTENDED TO CREATE TABLES ON THE DB, BUT IT 
RUNS AT THE SAME TIME THAN THE AUTOMATIC SCHEMA GENERATION, SO
THIS MAY CONFLICT WITH spring.jpa.hibernate.ddl-auto OR eclipselink.ddl-generation
CONFIGURATION; SO, IT'S USUALLY RECOMMENDED NOT TO USE THEM BOTH AT THE SAME TIME. 
BUT, IF WE KNOW WHAT WE ARE DOING (IE: LIKE CREATING JUST VIEWS, ALTHOUGH I'VE CHECKED IT DOES NOT WORK)
THERE SHOULD NOT BE ANY PROBLEM AT ALL
*/

-- CREATION OF THE SCHEMA ITSELF CANNOT BE DONE AUTOMATICALLY! 
-- IT MUST BE CREATED MANUALLY BEFORE RUNNING THE APP WITH THIS COMMAND:
-- CREATE SCHEMA IF NOT EXISTS `QuantUploaderCSFPR` DEFAULT CHARACTER SET utf8 ;
